lake-wg/edhoc

draft-ietf-lake-edhoc.md

Add test vectors for Static-Static DH - based on https://github.com/EricssonResearch/EDHOC/blob/4765c841ed14f2158edcd97940179e8f2dd06edb/Test%20Vectors/vectors.txt#L293

new test vectors

---

draft-ietf-lake-edhoc.md

Clarify hash computation in B.1

---

draft-ietf-lake-edhoc.md

add an appendix as per discussion in meeting today.
Probably the example should be retwigged (as it contains my obscure humour), and likely I've missed some of the detail that needs to be determined.

example applicability template

---

draft-ietf-lake-edhoc.md

Fixes typo in Section 4.4.3

---

draft-ietf-lake-edhoc.md

Rebase PR #98 and PR #122 on PR #129

Drop bstr_identifier rebased on PR #129

---

draft-ietf-lake-edhoc.md

CRED_x is not bstr

---

draft-ietf-lake-edhoc.md

There was quite a lot of overlap between 3.3.2 and 3.4. Tried to integrate 3.3.2 in 3.4 to avoid that.

Small restructure of 3.3 and 3.4

---

draft-ietf-lake-edhoc.md

Here is a rough first suggestion for changes.

Authentication parameters

---

draft-ietf-lake-edhoc.md

 Updated Internet Threat Model considerations (issue #198)

---

draft-ietf-lake-edhoc.md

 EAD internal structure and the EAD API (issue #186)

---

draft-ietf-lake-edhoc.md

Security considerations on connection IDs

---

draft-ietf-lake-edhoc.md

 Length of labels, removal of master (issue #204)

---

draft-ietf-lake-edhoc.md

 State diagram #224

---

draft-ietf-lake-edhoc.md

 Error message => Discontinue #208

---

draft-ietf-lake-edhoc.md

When does the Compliance requirements apply #238

Compliance requirements update #238

---

draft-ietf-lake-edhoc.md

Representation of bstr as 1-byte int

---

draft-ietf-lake-edhoc.md

Signed-off-by: David Navarro <david.navarro@ioterop.com>

Define new media type application/edhoc+cbor-seq, issue #262

---

draft-ietf-lake-edhoc.md

Deterministic encoding and decoding. CDDL

---

draft-ietf-lake-edhoc.md

Updates and consequential changes following comments by Loïc.

Input from Loïc

---

draft-ietf-lake-edhoc.md

Distinct padding names for each message

---

draft-ietf-lake-edhoc.md

Clarification of key identifier encoding

---

draft-ietf-lake-edhoc.md

 Updated EAD processing (critical and non-critical)

---

draft-ietf-lake-edhoc.md

#335. First text based on initial draft by Christian.

Implementation note about byte string identifier representation

---

draft-ietf-lake-edhoc.md

Large message_2

---

draft-ietf-lake-edhoc.md

Clarifying session key = PRK_out

---

draft-ietf-lake-edhoc.md

Updates following review by Malisa

---

draft-ietf-lake-edhoc.md

Genart review updates

---

draft-ietf-lake-edhoc.md

Having received several comments related to transport (#415, #417, #420, #422) and tried to address them in different PRs (#416, #425) and mails, especially [1], I got the impression that there seems to be some basic content missing from section 3.4. So I made an update. Comments are welcome!
[1] https://mailarchive.ietf.org/arch/msg/lake/wuoYFmItMlbtNMYzHDH1ZAOHlno/

Potential update to section 3.4 Transport

---

draft-ietf-lake-traces.md

Traces: IESG Murray Kucherawy's comments #449

Addressing Murray's IESG comments

---

draft-ietf-lake-traces.md

 Align with #446
